# Glacier - MIT License
background #2C323D
foreground #D8DEE9
selection_background #495F6C
selection_foreground #D8DEE9
cursor #88C0D0
cursor_text_color #2C323D
url_color #88C0D0
active_border_color #88C0D0
inactive_border_color #40495A
active_tab_background #2C323D
active_tab_foreground #D8DEE9
inactive_tab_background #252A34
inactive_tab_foreground #B9BFCA
color0 #40495A
color1 #DEAFB6
color2 #BEE4D1
color3 #E4DFBE
color4 #AFCBDE
color5 #C5AFDE
color6 #BEDFE4
color7 #C2C8D2
color8 #747A85
color9 #EBCBD0
color10 #DAF0E5
color11 #F0EEDA
color12 #CBDEEB
color13 #DACBEB
color14 #DAEEF0
color15 #EAEDF3
