# Dreams - MIT License
background #262834
foreground #F8F8F2
selection_background #564A73
selection_foreground #F8F8F2
cursor #BD93F9
cursor_text_color #262834
url_color #FF79C6
active_border_color #BD93F9
inactive_border_color #414456
active_tab_background #262834
active_tab_foreground #F8F8F2
inactive_tab_background #20212A
inactive_tab_foreground #D2D3D0
color0 #414456
color1 #F67992
color2 #8CF8AC
color3 #F4F88C
color4 #8392F7
color5 #D179F6
color6 #8CE2F8
color7 #DFDFDA
color8 #7E7F84
color9 #FA9DB0
color10 #B1FCC7
color11 #F9FCB1
color12 #A8B3FB
color13 #DF9DFA
color14 #B1EDFC
color15 #FBFBF8
