# Tidepool - MIT License
background #002934
foreground #93A1A1
selection_background #0C4867
selection_foreground #93A1A1
cursor #268BD2
cursor_text_color #002934
url_color #268BD2
active_border_color #268BD2
inactive_border_color #0A4958
active_tab_background #002934
active_tab_foreground #93A1A1
inactive_tab_background #001D24
inactive_tab_foreground #798B8D
color0 #0A4958
color1 #E76E72
color2 #58E4BA
color3 #E4B558
color4 #6196E5
color5 #E76AA8
color6 #58CDE4
color7 #849191
color8 #3E5B62
color9 #EF8F92
color10 #79ECC9
color11 #ECC579
color12 #82ADED
color13 #EF8BBD
color14 #79D9EC
color15 #C4CBCB
