# Fluffy Sky - MIT License
background #332445
foreground #FFF0F5
selection_background #743A69
selection_foreground #FFF0F5
cursor #FF69B4
cursor_text_color #332445
url_color #FF80AB
active_border_color #FF69B4
inactive_border_color #513C6E
active_tab_background #332445
active_tab_foreground #FFF0F5
inactive_tab_background #2B1E3E
inactive_tab_foreground #DACBD5
color0 #513C6E
color1 #F4909D
color2 #A2F6CF
color3 #F6E0A2
color4 #90BBF4
color5 #F490F1
color6 #A2F0F6
color7 #E6D8DC
color8 #897A8F
color9 #F9B4BD
color10 #C6FBE2
color11 #FBEDC6
color12 #B4D2F9
color13 #F9B4F7
color14 #C6F7FB
color15 #FFF7FA
