# Neon Arcade - MIT License
background #231A3A
foreground #E0E0FF
selection_background #693669
selection_foreground #E0E0FF
cursor #FF71CE
cursor_text_color #231A3A
url_color #F97E72
active_border_color #FF71CE
inactive_border_color #422966
active_tab_background #231A3A
active_tab_foreground #E0E0FF
inactive_tab_background #1D1631
inactive_tab_foreground #BEBCDC
color0 #422966
color1 #FF4778
color2 #7CFF5C
color3 #FFEF5C
color4 #6689FF
color5 #FF47DA
color6 #5CEFFF
color7 #CACAE6
color8 #726D8D
color9 #FF7096
color10 #9DFF85
color11 #FFF385
color12 #8FA8FF
color13 #FF70E2
color14 #85F3FF
color15 #EEEEFF
