# Textce - MIT License
[colors.primary]
background = "#2A2A2A"
foreground = "#E6E6E6"

[colors.cursor]
text = "#2A2A2A"
cursor = "#8E8E93"

[colors.selection]
text = "#E6E6E6"
background = "#4A4A4C"

[colors.normal]
black = "#3D3D3D"
red = "#C18E8B"
green = "#95C6A4"
yellow = "#C6B995"
blue = "#88A5BF"
magenta = "#B18FC3"
cyan = "#95C6BF"
white = "#CFCFCF"

[colors.bright]
black = "#797979"
red = "#D0A7A5"
green = "#AFD5BA"
yellow = "#D5CBAF"
blue = "#A2B9CE"
magenta = "#C4A9D2"
cyan = "#AFD5D0"
white = "#F1F1F1"
