# White - MIT License
background #FAFAFA
foreground #212121
selection_background #FDE27F
selection_foreground #212121
cursor #009688
cursor_text_color #FAFAFA
url_color #00838F
active_border_color #009688
inactive_border_color #E0E0E0
active_tab_background #FAFAFA
active_tab_foreground #212121
inactive_tab_background #F5F5F5
inactive_tab_foreground #484848
color0 #212121
color1 #D40000
color2 #1D823C
color3 #8A5F00
color4 #0058D6
color5 #9A2BD8
color6 #007D6D
color7 #E0E0E0
color8 #5E5E5E
color9 #DC3737
color10 #4E9C66
color11 #A38137
color12 #377CDE
color13 #AF59DF
color14 #37988C
color15 #EFEFEF
