# Hearth - MIT License
background #262626
foreground #EBDBB2
selection_background #6A5629
selection_foreground #EBDBB2
cursor #FABD2F
cursor_text_color #262626
url_color #83A598
active_border_color #FABD2F
inactive_border_color #3A3634
active_tab_background #262626
active_tab_foreground #EBDBB2
inactive_tab_background #1C1F20
inactive_tab_foreground #C8BA99
color0 #3A3634
color1 #DC7A6A
color2 #D5DC6A
color3 #DCB26A
color4 #5AC7D8
color5 #DF778F
color6 #6EDC6A
color7 #D4C5A0
color8 #797261
color9 #E69689
color10 #E0E689
color11 #E6C489
color12 #79D4E2
color13 #E896A9
color14 #8DE689
color15 #F4EBD5
