# BX - MIT License
background #000000
foreground #C0C0C0
selection_background #524500
selection_foreground #C0C0C0
cursor #FFD700
cursor_text_color #000000
url_color #00FFFF
active_border_color #FFD700
inactive_border_color #2A2A2A
active_tab_background #000000
active_tab_foreground #C0C0C0
inactive_tab_background #000000
inactive_tab_foreground #9D9D9D
color0 #2A2A2A
color1 #FF3D3D
color2 #52FF52
color3 #FFFF52
color4 #4272FF
color5 #FF3DFF
color6 #52FFFF
color7 #ADADAD
color8 #515151
color9 #FF6666
color10 #7BFF7B
color11 #FFFF7B
color12 #6B90FF
color13 #FF66FF
color14 #7BFFFF
color15 #DCDCDC
